[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }


 [[language]]
    name = "typescript"
    auto-format = true
    language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]


 [[language]]
    name = "tsx"
    auto-format = true
    language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]



 [[language]]
    name = "json"
    language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
